language: node_js
node_js:
  - "node"
install:
  - wget https://github.com/github/codeql-action/releases/latest/download/codeql-bundle-linux64.tar.gz -P ../
  - tar -xvzf ../codeql-bundle-linux64.tar.gz -C ../
  - ../codeql/codeql database create ../testrepo_codeqldb_js --language=javascript
  - ../codeql/codeql database analyze ../testrepo_codeqldb_js javascript-code-scanning.qls --sarif-category=javascript --format=sarif-latest --output=../testrepo-js.sarif  
  - ../codeql/codeql github upload-results --repository=hassank-mapbox/testrepo --ref=refs/heads/main --commit=`git rev-parse HEAD` --sarif=../testrepo-js.sarif
