language: node_js
node_js:
  - "node"
install:
  - echo Hello
  - pwd
  - wget https://github.com/github/codeql-action/releases/latest/download/codeql-bundle-linux64.tar.gz
  - ll
  - tar -xvzf codeql-bundle-linux64.tar.gz
  - ll
  - ./codeql resolve qlpacks
  
