language: node_js
node_js:
  - "node"
install:
  - echo Hello
  - pwd
  - wget https://github.com/github/codeql-action/releases/latest/download/codeql-bundle-linux64.tar.gz
  - ls -l
  - tar -xvzf codeql-bundle-linux64.tar.gz
  - ls -l
  - ./codeql/codeql database create /codeql-dbs/testrepojs --language=javascript
  - ./codeql/codeql database analyze /codeql-dbs/testrepojs javascript-code-scanning.qls --sarif-category=javascript --format=sarif-latest --output=testrepo-js.sarif  
  - git rev-parse HEAD
  - git rev-parse HEAD | ./codeql/codeql github upload-results --repository=hassank-mapbox/testrepo --ref=refs/heads/main --commit=`git rev-parse HEAD` --sarif=/temp/example-repo-js.sarif
